Forms and helpers
WCanirinka/re-former pull request #1
Opened 2019-12-17 22:31 UTC by WCanirinka

The project is about creating forms and helpers by creating a rails test application.

2019-12-17 22:33 UTC, WCanirinka commented
After applying linters to the project, we are now requesting for a code review for the project

2019-12-18 00:18 UTC, Ispirett requested changes
## status: Changes required :1st_place_medal: 
Great Job so far @WCanirinka  @300ms you done some great work.

There are just are few forms missing please see below.

2019-12-18 00:18 UTC, Ispirett commented on app/views/users/new.html.erb
> +    <%= form_for(@user) do |f| %>
!: You are missing the plan HTML form [requirement](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/user_form1.png) 
2: form tag form is missing [requirement](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/user_form_tag2.png)

2019-12-18 15:42 UTC, WCanirinka commented
We have applied the necessary changes and we are requesting for a new code review.

2019-12-18 20:44 UTC, WCanirinka reviewed
Requesting for a review

2019-12-18 23:27 UTC, mosaaleb approved these changes
### Approved :clap:

#### You can merge :+1: 

##### Muhammad Ebeid

2019-12-18 23:37 UTC, merged